language: cpp
compiler:
- gcc
- clang
sudo: true
script:
- cd out
- cmake ..
- make
before-install:
- sudo add-apt-repository -y ppa:team-xbmc/ppa
- sudo apt-get update -qq
- sudo apt-get install -y  libsdl2-dev
- sudo apt-get install -y  libsdl2-ttf-dev
- sudo apt-get install -y  libsdl2-mixer-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - clang
