language: cpp
before_install:
- sudo add-apt-repository "deb http://ppa.launchpad.net/zoogie/sdl2-snapshots/ubuntu precise main"
- sudo apt-get update
- sudo apt-get -y install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev
compiler:
- gcc
- clang
script:
- cd out
- cmake ..
- make
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - clang
