language: cpp
compiler:
- gcc
- clang
sudo: true
script:
- cd out
- cmake ..
- make
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - clang
    - libsdl2-dev
